# Generated by Django 5.0.6 on 2024-06-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0002_medicine_hospital_created_at_hospital_hos_ph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='rastriyaparichai_patra_no',
            new_name='bima_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='parent_phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='rastriyaparichai_issue_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_no',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='specilization',
            field=models.CharField(default='', max_length=200),
        ),
    ]
