# Generated by Django 5.0.6 on 2024-06-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0003_rename_rastriyaparichai_patra_no_patient_bima_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Hospital',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='specilization',
            field=models.CharField(max_length=200),
        ),
    ]
