# Generated by Django 5.0.6 on 2024-06-01 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0004_alter_appoinment_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bimapage.hospital'),
        ),
    ]
