# Generated by Django 5.0.6 on 2024-06-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0005_alter_appoinment_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bimapage.hospital'),
        ),
    ]
