# Generated by Django 5.0.6 on 2024-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0006_alter_appoinment_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='checkup_estimeted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opd',
            name='token_num',
            field=models.IntegerField(default=1),
        ),
    ]
