# Generated by Django 5.0.6 on 2024-06-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0007_alter_opd_checkup_estimeted_time_alter_opd_token_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkupresult',
            name='opd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bimapage.opd'),
        ),
        migrations.AlterField(
            model_name='opd',
            name='token_num',
            field=models.IntegerField(),
        ),
    ]
