# Generated by Django 5.0.6 on 2024-06-04 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0008_alter_checkupresult_opd_alter_opd_token_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkupresult',
            name='opd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkupresults', to='Bimapage.opd'),
        ),
    ]
