# Generated by Django 5.0.6 on 2024-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bimapage', '0009_alter_checkupresult_opd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_pic'),
        ),
    ]
